rev_lifeday_saun_dann = Creature:new {
	objectName = "",
	customName = "a strange old Men",
	faction = "",
	level = 100,
	chanceHit = 0.390000,
	damageMin = 290,
	damageMax = 300,
	baseXp = 2914,
	baseHAM = 8400,
	baseHAMmax = 10200,
	armor = 0,
	resists = {-1,-1,-1,-1,-1,-1,-1,-1,-1},
	meatType = "",
	meatAmount = 0,
	hideType = "",
	hideAmount = 0,
	boneType = "",
	boneAmount = 0,
	milk = 0,
	tamingChance = 0.000000,
	ferocity = 0,
	pvpBitmask = NONE,
	creatureBitmask = NONE,
	diet = HERBIVORE,
	templates = {"object/mobile/lifeday_saun_dann.iff"},
	conversationTemplate = "xmas_vendor_template",
	optionsBitmask = 264
}

CreatureTemplates:addCreatureTemplate(rev_lifeday_saun_dann, "rev_lifeday_saun_dann")