rev_cleaningdroid= Creature:new {
	objectName = "",
	customName = "Cleaning Droid HK01",
	socialGroup = "imperial",
	faction = "imperial",
	level = 80,
	chanceHit = 25,
	damageMin = 920,
	damageMax = 1050,
	baseXp = 2057,
	baseHAM = 32000,
	baseHAMmax = 42000,
	armor = 2,
	resists = {40,40,60,35,55,70,35,40,15},
	meatType = "",
	meatAmount = 0,
	hideType = "",
	hideAmount = 0,
	boneType = "",
	boneAmount = 0,
	milk = 0,
	tamingChance = 0,
	ferocity = 0,
	pvpBitmask = ATTACKABLE,
	creatureBitmask = PACK,
	optionsBitmask = 128,
	diet = HERBIVORE,
	scale = 1.3,
	templates = {"object/mobile/npe/npe_droid_k3i_buzzer.iff"},
	lootGroups = {},
	defaultWeapon = "object/weapon/ranged/droid/droid_droideka_ranged.iff",
	defaultAttack = "creaturerangedattack"
}

CreatureTemplates:addCreatureTemplate(rev_cleaningdroid, "rev_cleaningdroid")
