rev_hk47= Creature:new {
	objectName = "",
	customName = "HK47",
	socialGroup = "dungeon_creature",
	faction = "dungeon_creature",
	level = 80,
	chanceHit = 25,
	damageMin = 620,
	damageMax = 1150,
	baseXp = 50000,
	baseHAM = 22000,
	baseHAMmax = 32000,
	armor = 2,
	resists = {40,40,60,35,55,70,35,40,15},
	meatType = "",
	meatAmount = 0,
	hideType = "",
	hideAmount = 0,
	boneType = "",
	boneAmount = 0,
	milk = 0,
	tamingChance = 0,
	ferocity = 0,
	pvpBitmask = AGGRESSIVE + ATTACKABLE + ENEMY,
	creatureBitmask = PACK,
	optionsBitmask = 128,
	diet = HERBIVORE,
	scale = 1.3,
	templates = {"object/mobile/som/hk47.iff"},
	lootGroups = {},
	weapons = {"battle_droid_weapons"},
	conversationTemplate = "",
	attacks = merge(pistoleermaster,carbineermaster,brawlermaster),
}

CreatureTemplates:addCreatureTemplate(rev_hk47, "rev_hk47")
