rev_droid_4warning = Creature:new {
	objectName = "",
	customName = "Creature of the Past",
	socialGroup = "dungeon_creature",
	faction = "dungeon_creature",
	level = 80,
	chanceHit = 25,
	damageMin = 1620,
	damageMax = 1950,
	baseXp = 2057,
	baseHAM = 232000,
	baseHAMmax = 342000,
	armor = 2,
	resists = {40,40,60,35,55,70,35,40,35},
	meatType = "",
	meatAmount = 0,
	hideType = "",
	hideAmount = 0,
	boneType = "",
	boneAmount = 0,
	milk = 0,
	tamingChance = 0,
	ferocity = 0,
	pvpBitmask = AGGRESSIVE + ATTACKABLE + ENEMY,
	creatureBitmask = PACK,
	optionsBitmask = 128,
	diet = HERBIVORE,
	scale = 6,
	templates = {"object/mobile/npe/npe_droid_4warning.iff"},
	lootGroups = {},    
	conversationTemplate = "",
	defaultWeapon = "object/weapon/ranged/droid/droid_droideka_ranged.iff",
	defaultAttack = "creaturerangedattack"
}

CreatureTemplates:addCreatureTemplate(rev_droid_4warning, "rev_droid_4warning")
