rev_jawa = Creature:new {
	objectName = "@mob/creature_names:jawa",
	randomNameType = NAME_GENERIC_TAG,
	socialGroup = "jawa",
	faction = "jawa",
	level = 90,
	chanceHit = 55,
	damageMin = 1620,
	damageMax = 2150,
	baseXp = 3057,
	baseHAM = 42000,
	baseHAMmax = 52000,
	armor = 2,
	resists = {55,55,60,55,55,70,55,55,25},
	meatType = "",
	meatAmount = 0,
	hideType = "",
	hideAmount = 0,
	boneType = "",
	boneAmount = 0,
	milk = 0,
	tamingChance = 0,
	ferocity = 0,
	pvpBitmask = AGGRESSIVE + ATTACKABLE + ENEMY,
	creatureBitmask = KILLER + PACK,
	optionsBitmask = 128,
	diet = HERBIVORE,

	templates = {"object/mobile/jawa_male.iff"},
	lootGroups = {},
	weapons = {"jawa_ranged_weapons_heavy"},
	conversationTemplate = "",
	attacks = merge(bountyhuntermaster, commandomaster,tkamaster,rilfemanmaster,brawlermaster)
}

CreatureTemplates:addCreatureTemplate(rev_jawa, "rev_jawa")
