object_revelation_intangible_vehicle_landspeeder_ab1_pcd = object_revelation_intangible_vehicle_shared_landspeeder_ab1_pcd:new {

}

ObjectTemplates:addTemplate(object_revelation_intangible_vehicle_landspeeder_ab1_pcd, "object/intangible/vehicle/landspeeder_ab1_pcd.iff")
