object_revelation_tangible_furniture_decorative_hologram_nebulon_frigate = object_revelation_tangible_furniture_decorative_shared_hologram_nebulon_frigate:new {
customName = "Nebulon Frigate"
}

ObjectTemplates:addTemplate(object_revelation_tangible_furniture_decorative_hologram_nebulon_frigate, "object/tangible/furniture/decorative/hologram_nebulon_frigate.iff")
