object_revelation_mobile_lifeday_monkey_lizard = object_revelation_mobile_shared_lifeday_monkey_lizard:new {

}

ObjectTemplates:addTemplate(object_revelation_mobile_lifeday_monkey_lizard, "object/mobile/lifeday_monkey_lizard.iff")
