object_revelation_mobile_obi_wan_ghost_static = object_revelation_mobile_shared_obi_wan_ghost_static:new {

}

ObjectTemplates:addTemplate(object_revelation_mobile_obi_wan_ghost_static, "object/mobile/obi_wan_ghost_static.iff")
