object_revelation_mobile_outbreak_undead_deathtrooper_01_m = object_revelation_mobile_shared_outbreak_undead_deathtrooper_01_m:new {

}
ObjectTemplates:addTemplate(object_revelation_mobile_outbreak_undead_deathtrooper_01_m, "object/mobile/outbreak_undead_deathtrooper_01_m.iff")

