require "object.revelation.mobile.beast_master.serverobjects"
require "object.revelation.mobile.skeleton.serverobjects"
require "object.revelation.mobile.vehicle.serverobjects"
require "object.revelation.mobile.ep3.serverobjects"
require "object.revelation.mobile.npe.serverobjects"
require "object.revelation.mobile.som.serverobjects"
require "object.revelation.mobile.playercity.serverobjects"

require "object.revelation.mobile.atxt"
require "object.revelation.mobile.obi_wan_ghost_static"
require "object.revelation.mobile.outbreak_undead_boss_f_both_01"
require "object.revelation.mobile.outbreak_undead_boss_m_both_01"
require "object.revelation.mobile.outbreak_undead_boss_m_wke_01"
require "object.revelation.mobile.outbreak_undead_deathtrooper_01_m"
require "object.revelation.mobile.lifeday_monkey_lizard"
require "object.revelation.mobile.lifeday_saun_dann"