require("mobile.revelation.faction.rebel.at_xt")
require("mobile.revelation.faction.rebel.rev_rebel_army_captain")
require("mobile.revelation.faction.rebel.rev_rebel_sergeant")
require("mobile.revelation.faction.rebel.rev_rebel_commando")
require("mobile.revelation.faction.rebel.rev_rebel_trooper")
require("mobile.revelation.faction.rebel.rev_at_xt")
require("mobile.revelation.faction.rebel.rev_specops_trooper")
require("mobile.revelation.faction.rebel.rev_rebel_barracs_boss")
require("mobile.revelation.faction.rebel.rev_rebel_powersupply_boss")
require("mobile.revelation.faction.rebel.rev_rebel_bastion_boss")
require("mobile.revelation.faction.rebel.rev_rebel_battledroid")
require("mobile.revelation.faction.rebel.rev_spawnguard_at_xt")
require("mobile.revelation.faction.rebel.rev_reb_probot")
require("mobile.revelation.faction.rebel.rev_rebel_han_solo")
require("mobile.revelation.faction.rebel.rev_pvpevent_luke_skywalker")


