--Copyright (C) 2015 <www.revelationonline.net> Author matthias.muente@gmx.de
require "object.revelation.tangible.deed.vehicle_deed.barc_speeder_deed"
require "object.revelation.tangible.deed.vehicle_deed.pod_racer_one_deed"
require "object.revelation.tangible.deed.vehicle_deed.pod_racer_two_deed"
require "object.revelation.tangible.deed.vehicle_deed.barc_speeder_imperial_deed"
require "object.revelation.tangible.deed.vehicle_deed.barc_speeder_rebel_deed"
require "object.revelation.tangible.deed.vehicle_deed.swamp_speeder"
require "object.revelation.tangible.deed.vehicle_deed.basilisk_war_droid"
require "object.revelation.tangible.deed.vehicle_deed.hoverlifter_speeder"
require "object.revelation.tangible.deed.vehicle_deed.landspeeder_lava_skiff_deed"
require "object.revelation.tangible.deed.vehicle_deed.landspeeder_v35_deed"
require "object.revelation.tangible.deed.vehicle_deed.landspeeder_xp38_deed"
--require "object.revelation.tangible.deed.vehicle_deed.landspeeder_ab1_deed"
require "object.revelation.tangible.deed.vehicle_deed.sith_speeder_deed"
require "object.revelation.tangible.deed.vehicle_deed.stap_speeder_deed"