object_revelation_mobile_npe_npe_droid_i7construct = object_revelation_mobile_npe_shared_npe_droid_i7construct:new {

}
ObjectTemplates:addTemplate(object_revelation_mobile_npe_npe_droid_i7construct, "object/mobile/npe/npe_droid_i7construct.iff")

