object_revelation_mobile_npe_npe_droid_i10_probe = object_revelation_mobile_npe_shared_npe_droid_i10_probe:new {

}
ObjectTemplates:addTemplate(object_revelation_mobile_npe_npe_droid_i10_probe, "object/mobile/npe/npe_droid_i10_probe.iff")

