object_revelation_draft_schematic_armor_shared_armor_module_heavy = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_module_heavy.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_module_heavy, "object/draft_schematic/armor/shared_armor_module_heavy.iff")

object_revelation_draft_schematic_armor_shared_armor_module_light = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_module_light.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_module_light, "object/draft_schematic/armor/shared_armor_module_light.iff")

object_revelation_draft_schematic_armor_shared_armor_segment = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_segment.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_segment, "object/draft_schematic/armor/shared_armor_segment.iff")

object_revelation_draft_schematic_armor_shared_armor_segment_advanced = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_segment_advanced.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_segment_advanced, "object/draft_schematic/armor/shared_armor_segment_advanced.iff")

object_revelation_draft_schematic_armor_shared_armor_segment_bone = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_segment_bone.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_segment_bone, "object/draft_schematic/armor/shared_armor_segment_bone.iff")

object_revelation_draft_schematic_armor_shared_armor_segment_bone_acklay = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_segment_bone_acklay.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_segment_bone_acklay, "object/draft_schematic/armor/shared_armor_segment_bone_acklay.iff")

object_revelation_draft_schematic_armor_shared_armor_segment_bone_advanced = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_segment_bone_advanced.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_segment_bone_advanced, "object/draft_schematic/armor/shared_armor_segment_bone_advanced.iff")

object_revelation_draft_schematic_armor_shared_armor_segment_chitin = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_segment_chitin.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_segment_chitin, "object/draft_schematic/armor/shared_armor_segment_chitin.iff")

object_revelation_draft_schematic_armor_shared_armor_segment_chitin_advanced = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_segment_chitin_advanced.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_segment_chitin_advanced, "object/draft_schematic/armor/shared_armor_segment_chitin_advanced.iff")

object_revelation_draft_schematic_armor_shared_armor_segment_composite = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_segment_composite.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_segment_composite, "object/draft_schematic/armor/shared_armor_segment_composite.iff")

object_revelation_draft_schematic_armor_shared_armor_segment_composite_advanced = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_segment_composite_advanced.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_segment_composite_advanced, "object/draft_schematic/armor/shared_armor_segment_composite_advanced.iff")

object_revelation_draft_schematic_armor_shared_armor_segment_kashyyykian_black_mtn = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_segment_kashyyykian_black_mtn.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_segment_kashyyykian_black_mtn, "object/draft_schematic/armor/shared_armor_segment_kashyyykian_black_mtn.iff")

object_revelation_draft_schematic_armor_shared_armor_segment_kashyyykian_black_mtn_advanced = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_segment_kashyyykian_black_mtn_advanced.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_segment_kashyyykian_black_mtn_advanced, "object/draft_schematic/armor/shared_armor_segment_kashyyykian_black_mtn_advanced.iff")

object_revelation_draft_schematic_armor_shared_armor_segment_kashyyykian_ceremonial = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_segment_kashyyykian_ceremonial.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_segment_kashyyykian_ceremonial, "object/draft_schematic/armor/shared_armor_segment_kashyyykian_ceremonial.iff")

object_revelation_draft_schematic_armor_shared_armor_segment_kashyyykian_ceremonial_advanced = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_segment_kashyyykian_ceremonial_advanced.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_segment_kashyyykian_ceremonial_advanced, "object/draft_schematic/armor/shared_armor_segment_kashyyykian_ceremonial_advanced.iff")

object_revelation_draft_schematic_armor_shared_armor_segment_kashyyykian_hunting = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_segment_kashyyykian_hunting.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_segment_kashyyykian_hunting, "object/draft_schematic/armor/shared_armor_segment_kashyyykian_hunting.iff")

object_revelation_draft_schematic_armor_shared_armor_segment_kashyyykian_hunting_advanced = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_segment_kashyyykian_hunting_advanced.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_segment_kashyyykian_hunting_advanced, "object/draft_schematic/armor/shared_armor_segment_kashyyykian_hunting_advanced.iff")

object_revelation_draft_schematic_armor_shared_armor_segment_padded = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_segment_padded.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_segment_padded, "object/draft_schematic/armor/shared_armor_segment_padded.iff")

object_revelation_draft_schematic_armor_shared_armor_segment_padded_advanced = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_segment_padded_advanced.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_segment_padded_advanced, "object/draft_schematic/armor/shared_armor_segment_padded_advanced.iff")

object_revelation_draft_schematic_armor_shared_armor_segment_ris = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_segment_ris.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_segment_ris, "object/draft_schematic/armor/shared_armor_segment_ris.iff")

object_revelation_draft_schematic_armor_shared_armor_segment_ris_acklay = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_segment_ris_acklay.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_segment_ris_acklay, "object/draft_schematic/armor/shared_armor_segment_ris_acklay.iff")

object_revelation_draft_schematic_armor_shared_armor_segment_ubese = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_segment_ubese.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_segment_ubese, "object/draft_schematic/armor/shared_armor_segment_ubese.iff")

object_revelation_draft_schematic_armor_shared_armor_segment_ubese_advanced = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_segment_ubese_advanced.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_segment_ubese_advanced, "object/draft_schematic/armor/shared_armor_segment_ubese_advanced.iff")

object_revelation_draft_schematic_armor_shared_armor_segment_zam = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_segment_zam.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_segment_zam, "object/draft_schematic/armor/shared_armor_segment_zam.iff")

object_revelation_draft_schematic_armor_shared_armor_segment_zam_advanced = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_segment_zam_advanced.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_segment_zam_advanced, "object/draft_schematic/armor/shared_armor_segment_zam_advanced.iff")

object_revelation_draft_schematic_armor_shared_shield_generator_facility = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_shield_generator_facility.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_shield_generator_facility, "object/draft_schematic/armor/shared_shield_generator_facility.iff")

object_revelation_draft_schematic_armor_shared_shield_generator_personal = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_shield_generator_personal.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_shield_generator_personal, "object/draft_schematic/armor/shared_shield_generator_personal.iff")

object_revelation_draft_schematic_armor_shared_shield_generator_personal_b = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_shield_generator_personal_b.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_shield_generator_personal_b, "object/draft_schematic/armor/shared_shield_generator_personal_b.iff")

object_revelation_draft_schematic_armor_shared_shield_generator_personal_c = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_shield_generator_personal_c.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_shield_generator_personal_c, "object/draft_schematic/armor/shared_shield_generator_personal_c.iff")

object_revelation_draft_schematic_armor_shared_shield_generator_personal_imperial_test = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_shield_generator_personal_imperial_test.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_shield_generator_personal_imperial_test, "object/draft_schematic/armor/shared_shield_generator_personal_imperial_test.iff")

object_revelation_draft_schematic_armor_shared_shield_generator_vehicular = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_shield_generator_vehicular.iff"
}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_shield_generator_vehicular, "object/draft_schematic/armor/shared_shield_generator_vehicular.iff")

--Assault Trooper
object_revelation_draft_schematic_armor_shared_armor_appearance_assault_trooper_helmet = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_assault_trooper_helmet.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_assault_trooper_helmet, "object/draft_schematic/armor/shared_armor_appearance_assault_trooper_helmet.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_assault_trooper_bicep_l = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_assault_trooper_bicep_l.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_assault_trooper_bicep_l, "object/draft_schematic/armor/shared_armor_appearance_assault_trooper_bicep_l.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_assault_trooper_bicep_r = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_assault_trooper_bicep_r.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_assault_trooper_bicep_r, "object/draft_schematic/armor/shared_armor_appearance_assault_trooper_bicep_r.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_assault_trooper_bracer_r = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_assault_trooper_bracer_r.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_assault_trooper_bracer_r, "object/draft_schematic/armor/shared_armor_appearance_assault_trooper_bracer_r.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_assault_trooper_bracer_l = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_assault_trooper_bracer_l.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_assault_trooper_bracer_l, "object/draft_schematic/armor/shared_armor_appearance_assault_trooper_bracer_l.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_assault_trooper_boots = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_assault_trooper_boots.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_assault_trooper_boots, "object/draft_schematic/armor/shared_armor_appearance_assault_trooper_boots.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_assault_trooper_chest = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_assault_trooper_chest.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_assault_trooper_chest, "object/draft_schematic/armor/shared_armor_appearance_assault_trooper_chest.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_assault_trooper_gloves = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_assault_trooper_gloves.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_assault_trooper_gloves, "object/draft_schematic/armor/shared_armor_appearance_assault_trooper_gloves.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_assault_trooper_leggings = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_assault_trooper_leggings.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_assault_trooper_leggings, "object/draft_schematic/armor/shared_armor_appearance_assault_trooper_leggings.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_assault_trooper_utility_belt = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_assault_trooper_utility_belt.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_assault_trooper_utility_belt, "object/draft_schematic/armor/shared_armor_appearance_assault_trooper_utility_belt.iff")

--Scout Trooper
object_revelation_draft_schematic_armor_shared_armor_appearance_scout_trooper_helmet = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_scout_trooper_helmet.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_scout_trooper_helmet, "object/draft_schematic/armor/shared_armor_appearance_scout_trooper_helmet.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_scout_trooper_bicep_l = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_scout_trooper_bicep_l.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_scout_trooper_bicep_l, "object/draft_schematic/armor/shared_armor_appearance_scout_trooper_bicep_l.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_scout_trooper_bicep_r = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_scout_trooper_bicep_r.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_scout_trooper_bicep_r, "object/draft_schematic/armor/shared_armor_appearance_scout_trooper_bicep_r.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_scout_trooper_bracer_r = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_scout_trooper_bracer_r.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_scout_trooper_bracer_r, "object/draft_schematic/armor/shared_armor_appearance_scout_trooper_bracer_r.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_scout_trooper_bracer_l = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_scout_trooper_bracer_l.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_scout_trooper_bracer_l, "object/draft_schematic/armor/shared_armor_appearance_scout_trooper_bracer_l.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_scout_trooper_boots = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_scout_trooper_boots.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_scout_trooper_boots, "object/draft_schematic/armor/shared_armor_appearance_scout_trooper_boots.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_scout_trooper_chest = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_scout_trooper_chest.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_scout_trooper_chest, "object/draft_schematic/armor/shared_armor_appearance_scout_trooper_chest.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_scout_trooper_gloves = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_scout_trooper_gloves.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_scout_trooper_gloves, "object/draft_schematic/armor/shared_armor_appearance_scout_trooper_gloves.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_scout_trooper_leggings = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_scout_trooper_leggings.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_scout_trooper_leggings, "object/draft_schematic/armor/shared_armor_appearance_scout_trooper_leggings.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_scout_trooper_utility_belt = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_scout_trooper_utility_belt.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_scout_trooper_utility_belt, "object/draft_schematic/armor/shared_armor_appearance_scout_trooper_utility_belt.iff")


--Stormtrooper
object_revelation_draft_schematic_armor_shared_armor_appearance_stormtrooper_helmet = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_stormtrooper_helmet.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_stormtrooper_helmet, "object/draft_schematic/armor/shared_armor_appearance_stormtrooper_helmet.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_stormtrooper_bicep_l = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_stormtrooper_bicep_l.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_stormtrooper_bicep_l, "object/draft_schematic/armor/shared_armor_appearance_stormtrooper_bicep_l.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_stormtrooper_bicep_r = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_stormtrooper_bicep_r.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_stormtrooper_bicep_r, "object/draft_schematic/armor/shared_armor_appearance_stormtrooper_bicep_r.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_stormtrooper_bracer_r = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_stormtrooper_bracer_r.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_stormtrooper_bracer_r, "object/draft_schematic/armor/shared_armor_appearance_stormtrooper_bracer_r.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_stormtrooper_bracer_l = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_stormtrooper_bracer_l.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_stormtrooper_bracer_l, "object/draft_schematic/armor/shared_armor_appearance_stormtrooper_bracer_l.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_stormtrooper_boots = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_stormtrooper_boots.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_stormtrooper_boots, "object/draft_schematic/armor/shared_armor_appearance_stormtrooper_boots.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_stormtrooper_chest = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_stormtrooper_chest.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_stormtrooper_chest, "object/draft_schematic/armor/shared_armor_appearance_stormtrooper_chest.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_stormtrooper_gloves = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_stormtrooper_gloves.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_stormtrooper_gloves, "object/draft_schematic/armor/shared_armor_appearance_stormtrooper_gloves.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_stormtrooper_leggings = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_stormtrooper_leggings.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_stormtrooper_leggings, "object/draft_schematic/armor/shared_armor_appearance_stormtrooper_leggings.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_stormtrooper_utility_belt = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_stormtrooper_utility_belt.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_stormtrooper_utility_belt, "object/draft_schematic/armor/shared_armor_appearance_stormtrooper_utility_belt.iff")

--Rebel Assault
object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_assault_helmet = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_assault_helmet.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_assault_helmet, "object/draft_schematic/armor/shared_armor_appearance_rebel_assault_helmet.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_assault_bicep_l = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_assault_bicep_l.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_assault_bicep_l, "object/draft_schematic/armor/shared_armor_appearance_rebel_assault_bicep_l.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_assault_bicep_r = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_assault_bicep_r.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_assault_bicep_r, "object/draft_schematic/armor/shared_armor_appearance_rebel_assault_bicep_r.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_assault_bracer_r = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_assault_bracer_r.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_assault_bracer_r, "object/draft_schematic/armor/shared_armor_appearance_rebel_assault_bracer_r.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_assault_bracer_l = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_assault_bracer_l.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_assault_bracer_l, "object/draft_schematic/armor/shared_armor_appearance_rebel_assault_bracer_l.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_assault_boots = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_assault_boots.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_assault_boots, "object/draft_schematic/armor/shared_armor_appearance_rebel_assault_boots.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_assault_chest = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_assault_chest.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_assault_chest, "object/draft_schematic/armor/shared_armor_appearance_rebel_assault_chest.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_assault_gloves = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_assault_gloves.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_assault_gloves, "object/draft_schematic/armor/shared_armor_appearance_rebel_assault_gloves.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_assault_leggings = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_assault_leggings.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_assault_leggings, "object/draft_schematic/armor/shared_armor_appearance_rebel_assault_leggings.iff")

--Rebel Snow
object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_snow_helmet = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_snow_helmet.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_snow_helmet, "object/draft_schematic/armor/shared_armor_appearance_rebel_snow_helmet.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_snow_bicep_l = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_snow_bicep_l.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_snow_bicep_l, "object/draft_schematic/armor/shared_armor_appearance_rebel_snow_bicep_l.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_snow_bicep_r = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_snow_bicep_r.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_snow_bicep_r, "object/draft_schematic/armor/shared_armor_appearance_rebel_snow_bicep_r.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_snow_bracer_r = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_snow_bracer_r.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_snow_bracer_r, "object/draft_schematic/armor/shared_armor_appearance_rebel_snow_bracer_r.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_snow_bracer_l = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_snow_bracer_l.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_snow_bracer_l, "object/draft_schematic/armor/shared_armor_appearance_rebel_snow_bracer_l.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_snow_boots = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_snow_boots.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_snow_boots, "object/draft_schematic/armor/shared_armor_appearance_rebel_snow_boots.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_snow_chest = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_snow_chest.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_snow_chest, "object/draft_schematic/armor/shared_armor_appearance_rebel_snow_chest.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_snow_gloves = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_snow_gloves.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_snow_gloves, "object/draft_schematic/armor/shared_armor_appearance_rebel_snow_gloves.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_snow_leggings = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_snow_leggings.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_snow_leggings, "object/draft_schematic/armor/shared_armor_appearance_rebel_snow_leggings.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_snow_belt = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_snow_belt.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_snow_belt, "object/draft_schematic/armor/shared_armor_appearance_rebel_snow_belt.iff")

--Snowtrooper
object_revelation_draft_schematic_armor_shared_armor_appearance_snowtrooper_helmet = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_snowtrooper_helmet.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_snowtrooper_helmet, "object/draft_schematic/armor/shared_armor_appearance_snowtrooper_helmet.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_snowtrooper_bicep_l = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_snowtrooper_bicep_l.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_snowtrooper_bicep_l, "object/draft_schematic/armor/shared_armor_appearance_snowtrooper_bicep_l.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_snowtrooper_bicep_r = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_snowtrooper_bicep_r.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_snowtrooper_bicep_r, "object/draft_schematic/armor/shared_armor_appearance_snowtrooper_bicep_r.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_snowtrooper_bracer_r = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_snowtrooper_bracer_r.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_snowtrooper_bracer_r, "object/draft_schematic/armor/shared_armor_appearance_snowtrooper_bracer_r.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_snowtrooper_bracer_l = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_snowtrooper_bracer_l.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_snowtrooper_bracer_l, "object/draft_schematic/armor/shared_armor_appearance_snowtrooper_bracer_l.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_snowtrooper_boots = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_snowtrooper_boots.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_snowtrooper_boots, "object/draft_schematic/armor/shared_armor_appearance_snowtrooper_boots.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_snowtrooper_chest = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_snowtrooper_chest.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_snowtrooper_chest, "object/draft_schematic/armor/shared_armor_appearance_snowtrooper_chest.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_snowtrooper_gloves = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_snowtrooper_gloves.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_snowtrooper_gloves, "object/draft_schematic/armor/shared_armor_appearance_snowtrooper_gloves.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_snowtrooper_leggings = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_snowtrooper_leggings.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_snowtrooper_leggings, "object/draft_schematic/armor/shared_armor_appearance_snowtrooper_leggings.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_snowtrooper_utility_belt = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_snowtrooper_utility_belt.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_snowtrooper_utility_belt, "object/draft_schematic/armor/shared_armor_appearance_snowtrooper_utility_belt.iff")

--Rebel Battle
object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_battle_helmet = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_battle_helmet.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_battle_helmet, "object/draft_schematic/armor/shared_armor_appearance_rebel_battle_helmet.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_battle_bicep_l = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_battle_bicep_l.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_battle_bicep_l, "object/draft_schematic/armor/shared_armor_appearance_rebel_battle_bicep_l.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_battle_bicep_r = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_battle_bicep_r.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_battle_bicep_r, "object/draft_schematic/armor/shared_armor_appearance_rebel_battle_bicep_r.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_battle_bracer_r = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_battle_bracer_r.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_battle_bracer_r, "object/draft_schematic/armor/shared_armor_appearance_rebel_battle_bracer_r.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_battle_bracer_l = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_battle_bracer_l.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_battle_bracer_l, "object/draft_schematic/armor/shared_armor_appearance_rebel_battle_bracer_l.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_battle_boots = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_battle_boots.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_battle_boots, "object/draft_schematic/armor/shared_armor_appearance_rebel_battle_boots.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_battle_chest = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_battle_chest.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_battle_chest, "object/draft_schematic/armor/shared_armor_appearance_rebel_battle_chest.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_battle_gloves = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_battle_gloves.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_battle_gloves, "object/draft_schematic/armor/shared_armor_appearance_rebel_battle_gloves.iff")

object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_battle_leggings = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/armor/shared_armor_appearance_rebel_battle_leggings.iff"
	}

ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_armor_shared_armor_appearance_rebel_battle_leggings, "object/draft_schematic/armor/shared_armor_appearance_rebel_battle_leggings.iff")

