--Copyright (C) 2015 <www.revelationonline.net> Author genesis@revelationonline.net


--which carries forward this exception.

-- Belt

object_revelation_tangible_wearables_armor_mandalorian_imperial_shared_armor_mandalorian_imperial_belt = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/mandalorian_imperial/shared_armor_mandalorian_imperial_belt.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_mandalorian_imperial_shared_armor_mandalorian_imperial_belt, "object/tangible/wearables/armor/mandalorian_imperial/shared_armor_mandalorian_imperial_belt.iff")

-- Bicep Left

object_revelation_tangible_wearables_armor_mandalorian_imperial_shared_armor_mandalorian_imperial_bicep_l = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/mandalorian_imperial/shared_armor_mandalorian_imperial_bicep_l.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_mandalorian_imperial_shared_armor_mandalorian_imperial_bicep_l, "object/tangible/wearables/armor/mandalorian_imperial/shared_armor_mandalorian_imperial_bicep_l.iff")

--Bicep Right

object_revelation_tangible_wearables_armor_mandalorian_imperial_shared_armor_mandalorian_imperial_bicep_r = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/mandalorian_imperial/shared_armor_mandalorian_imperial_bicep_r.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_mandalorian_imperial_shared_armor_mandalorian_imperial_bicep_r, "object/tangible/wearables/armor/mandalorian_imperial/shared_armor_mandalorian_imperial_bicep_r.iff")

--Bracer Left

object_revelation_tangible_wearables_armor_mandalorian_imperial_shared_armor_mandalorian_imperial_bracer_l = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/mandalorian_imperial/shared_armor_mandalorian_imperial_bracer_l.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_mandalorian_imperial_shared_armor_mandalorian_imperial_bracer_l, "object/tangible/wearables/armor/mandalorian_imperial/shared_armor_mandalorian_imperial_bracer_l.iff")

-- Bracer Right

object_revelation_tangible_wearables_armor_mandalorian_imperial_shared_armor_mandalorian_imperial_bracer_r = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/mandalorian_imperial/shared_armor_mandalorian_imperial_bracer_r.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_mandalorian_imperial_shared_armor_mandalorian_imperial_bracer_r, "object/tangible/wearables/armor/mandalorian_imperial/shared_armor_mandalorian_imperial_bracer_r.iff")

--Chest Plate

object_revelation_tangible_wearables_armor_mandalorian_imperial_shared_armor_mandalorian_imperial_chest_plate = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/mandalorian_imperial/shared_armor_mandalorian_imperial_chest_plate.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_mandalorian_imperial_shared_armor_mandalorian_imperial_chest_plate, "object/tangible/wearables/armor/mandalorian_imperial/shared_armor_mandalorian_imperial_chest_plate.iff")

--Gloves

object_revelation_tangible_wearables_armor_mandalorian_imperial_shared_armor_mandalorian_imperial_gloves = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/mandalorian_imperial/shared_armor_mandalorian_imperial_gloves.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_mandalorian_imperial_shared_armor_mandalorian_imperial_gloves, "object/tangible/wearables/armor/mandalorian_imperial/shared_armor_mandalorian_imperial_gloves.iff")

--Helmet

object_revelation_tangible_wearables_armor_mandalorian_imperial_shared_armor_mandalorian_imperial_helmet = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/mandalorian_imperial/shared_armor_mandalorian_imperial_helmet.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_mandalorian_imperial_shared_armor_mandalorian_imperial_helmet, "object/tangible/wearables/armor/mandalorian_imperial/shared_armor_mandalorian_imperial_helmet.iff")

--Leggings

object_revelation_tangible_wearables_armor_mandalorian_imperial_shared_armor_mandalorian_imperial_leggings = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/mandalorian_imperial/shared_armor_mandalorian_imperial_leggings.iff"

}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_mandalorian_imperial_shared_armor_mandalorian_imperial_leggings, "object/tangible/wearables/armor/mandalorian_imperial/shared_armor_mandalorian_imperial_leggings.iff")

--Boots

object_revelation_tangible_wearables_armor_mandalorian_imperial_shared_armor_mandalorian_imperial_boots = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/mandalorian_imperial/shared_armor_mandalorian_imperial_boots.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_mandalorian_imperial_shared_armor_mandalorian_imperial_boots, "object/tangible/wearables/armor/mandalorian_imperial/shared_armor_mandalorian_imperial_boots.iff")
