--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

color_crystal_moragshearth = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "Morags Hearth",
	directObjectTemplate = "object/tangible/component/weapon/lightsaber/lightsaber_module_force_crystal.iff",
	craftingValues = {
		{"hitpoints",650,750,0},
		{"color",33,33,0},
		{"mindamage",2,5,0},
		{"maxdamage",3,6,0},
		{"forcecost",0,3,0},
	},

	customizationStringNames = {},
	customizationValues = {}
}

addLootItemTemplate("color_crystal_moragshearth", color_crystal_moragshearth)