easy_czerka_outpost_controlled_technician = Creature:new {
	objectName = "",
	customName = "Mindcontrolled Technican",
	socialGroup = "dungeon_creature",
	faction = "",
	level = 60,
	chanceHit = 30,
	damageMin = 545,
	damageMax = 800,
	baseXp = 9336,
	baseHAM = 14000,
	baseHAMmax = 19000,
	armor = 0,
	resists = {0,0,0,0,0,0,0,0,-1},
	meatType = "",
	meatAmount = 0,
	hideType = "",
	hideAmount = 0,
	boneType = "",
	boneAmount = 0,
	milk = 0,
	tamingChance = 0,
	ferocity = 0,
	pvpBitmask = AGGRESSIVE + ATTACKABLE,
	creatureBitmask = PACK,
	optionsBitmask = 128,
	diet = HERBIVORE,

	templates = {"object/mobile/dressed_mand_bunker_technician.iff"},
	lootGroups = {},
	weapons = {},
	conversationTemplate = "",
	attacks = merge(brawlermaster),
}

CreatureTemplates:addCreatureTemplate(easy_czerka_outpost_controlled_technician, "easy_czerka_outpost_controlled_technician")
