hard_czerka_outpost_controlled_technician = Creature:new {
	objectName = "",
	customName = "Mindcontrolled Technican",
	socialGroup = "dungeon_creature",
	faction = "",
	level = 100,
	chanceHit = 50,
	damageMin = 745,
	damageMax = 1000,
	baseXp = 9336,
	baseHAM = 34000,
	baseHAMmax = 39000,
	armor = 0,
	resists = {0,0,0,0,0,0,0,0,-1},
	meatType = "",
	meatAmount = 0,
	hideType = "",
	hideAmount = 0,
	boneType = "",
	boneAmount = 0,
	milk = 0,
	tamingChance = 0,
	ferocity = 0,
	pvpBitmask = AGGRESSIVE + ATTACKABLE,
	creatureBitmask = PACK,
	optionsBitmask = 128,
	diet = HERBIVORE,

	templates = {"object/mobile/dressed_mand_bunker_technician.iff"},
	lootGroups = {},
	weapons = {},
	conversationTemplate = "",
	attacks = merge(brawlermaster),
}

CreatureTemplates:addCreatureTemplate(hard_czerka_outpost_controlled_technician, "hard_czerka_outpost_controlled_technician")
