require("mobile.revelation.czerka_outpost.czerka_outpost_at_st")
require("mobile.revelation.czerka_outpost.czerka_outpost_guard")
require("mobile.revelation.czerka_outpost.czerka_outpost_lieutenant")
require("mobile.revelation.czerka_outpost.hard_czerka_outpost_guard")
require("mobile.revelation.czerka_outpost.hard_czerka_outpost_lieutenant")
require("mobile.revelation.czerka_outpost.czerka_outpost_captain")
require("mobile.revelation.czerka_outpost.czerka_outpost_technician")
require("mobile.revelation.czerka_outpost.czerka_outpost_scientist")
require("mobile.revelation.czerka_outpost.czerka_outpost_guard_r")
require("mobile.revelation.czerka_outpost.czerka_outpost_lieutenant_r")
require("mobile.revelation.czerka_outpost.hard_czerka_outpost_guard_r")
require("mobile.revelation.czerka_outpost.hard_czerka_outpost_lieutenant_r")
require("mobile.revelation.czerka_outpost.czerka_outpost_captain_r")

-- village fs people
require("mobile.revelation.czerka_outpost.czerka_outpost_whip")
require("mobile.revelation.czerka_outpost.czerka_outpost_sivarra_mechaux")
require("mobile.revelation.czerka_outpost.czerka_outpost_rohak_village_elder")
require("mobile.revelation.czerka_outpost.czerka_outpost_quharek")
require("mobile.revelation.czerka_outpost.czerka_outpost_paemos")
require("mobile.revelation.czerka_outpost.czerka_outpost_noldan")
require("mobile.revelation.czerka_outpost.czerka_outpost_captain_sarguillo")

-- taskgiver Jediaccess
require("mobile.revelation.czerka_outpost.czerka_outpost_officer_kenny")

-- yavin outpost
require("mobile.revelation.czerka_outpost.czerka_yavin_mite_soldier")
require("mobile.revelation.czerka_outpost.czerka_yavin_mite_queen")
require("mobile.revelation.czerka_outpost.czerka_yavin_mite_harvester")
-- pirate outpost
require("mobile.revelation.czerka_outpost.czerka_outpost_droideka")
require("mobile.revelation.czerka_outpost.czerka_outpost_fed_battle_droid")
require("mobile.revelation.czerka_outpost.czerka_outpost_pirate")
require("mobile.revelation.czerka_outpost.czerka_outpost_pirate_crewman")
require("mobile.revelation.czerka_outpost.czerka_outpost_pirate_r")
require("mobile.revelation.czerka_outpost.czerka_outpost_pirate_crewman_r")
require("mobile.revelation.czerka_outpost.czerka_outpost_pirate_leader")
require("mobile.revelation.czerka_outpost.czerka_outpost_pirate_lieutenant")
require("mobile.revelation.czerka_outpost.czerka_outpost_slave")
require("mobile.revelation.czerka_outpost.czerka_outpost_slave_cf")

-- conversing droid
require("mobile.revelation.czerka_outpost.defect_e5")

--mining
require("mobile.revelation.czerka_outpost.czerka_outpost_mining_minecrawler_queen")
require("mobile.revelation.czerka_outpost.czerka_outpost_mining_minecrawler_brain")
require("mobile.revelation.czerka_outpost.czerka_outpost_mining_minecrawler_guardian")
require("mobile.revelation.czerka_outpost.czerka_outpost_mining_minecrawler_soldier")
require("mobile.revelation.czerka_outpost.czerka_outpost_mining_minecrawler")
require("mobile.revelation.czerka_outpost.czerka_outpost_mining_minecrawler_bonecrusher")
require("mobile.revelation.czerka_outpost.czerka_outpost_lift_worker")
require("mobile.revelation.czerka_outpost.czerka_outpost_miner")
require("mobile.revelation.czerka_outpost.czerka_outpost_controlled_guard")
require("mobile.revelation.czerka_outpost.czerka_outpost_controlled_lieutenant")
require("mobile.revelation.czerka_outpost.czerka_outpost_controlled_captain")
require("mobile.revelation.czerka_outpost.czerka_outpost_controlled_technician")
require("mobile.revelation.czerka_outpost.czerka_outpost_controlled_miner")
require("mobile.revelation.czerka_outpost.hard_czerka_outpost_mining_minecrawler_queen")
require("mobile.revelation.czerka_outpost.hard_czerka_outpost_mining_minecrawler_brain")
require("mobile.revelation.czerka_outpost.hard_czerka_outpost_mining_minecrawler_guardian")
require("mobile.revelation.czerka_outpost.hard_czerka_outpost_mining_minecrawler_soldier")
require("mobile.revelation.czerka_outpost.hard_czerka_outpost_mining_minecrawler")
require("mobile.revelation.czerka_outpost.hard_czerka_outpost_mining_minecrawler_bonecrusher")
require("mobile.revelation.czerka_outpost.hard_czerka_outpost_controlled_guard")
require("mobile.revelation.czerka_outpost.hard_czerka_outpost_controlled_lieutenant")
require("mobile.revelation.czerka_outpost.hard_czerka_outpost_controlled_captain")
require("mobile.revelation.czerka_outpost.hard_czerka_outpost_controlled_technician")
require("mobile.revelation.czerka_outpost.hard_czerka_outpost_controlled_miner")
require("mobile.revelation.czerka_outpost.hard_czerka_outpost_controlled_guard_r")
require("mobile.revelation.czerka_outpost.hard_czerka_outpost_controlled_lieutenant_r")
require("mobile.revelation.czerka_outpost.hard_czerka_outpost_controlled_captain_r")
require("mobile.revelation.czerka_outpost.czerka_outpost_controlled_guard_r")
require("mobile.revelation.czerka_outpost.czerka_outpost_controlled_lieutenant_r")
require("mobile.revelation.czerka_outpost.czerka_outpost_controlled_captain_r")

require("mobile.revelation.czerka_outpost.easy_czerka_outpost_mining_minecrawler_queen")
require("mobile.revelation.czerka_outpost.easy_czerka_outpost_mining_minecrawler_brain")
require("mobile.revelation.czerka_outpost.easy_czerka_outpost_mining_minecrawler_guardian")
require("mobile.revelation.czerka_outpost.easy_czerka_outpost_mining_minecrawler_soldier")
require("mobile.revelation.czerka_outpost.easy_czerka_outpost_mining_minecrawler")
require("mobile.revelation.czerka_outpost.easy_czerka_outpost_mining_minecrawler_bonecrusher")
require("mobile.revelation.czerka_outpost.easy_czerka_outpost_controlled_guard")
require("mobile.revelation.czerka_outpost.easy_czerka_outpost_controlled_lieutenant")
require("mobile.revelation.czerka_outpost.easy_czerka_outpost_controlled_captain")
require("mobile.revelation.czerka_outpost.easy_czerka_outpost_controlled_technician")
require("mobile.revelation.czerka_outpost.easy_czerka_outpost_controlled_miner")
require("mobile.revelation.czerka_outpost.easy_czerka_outpost_controlled_guard_r")
require("mobile.revelation.czerka_outpost.easy_czerka_outpost_controlled_lieutenant_r")
require("mobile.revelation.czerka_outpost.easy_czerka_outpost_controlled_captain_r")

require("mobile.revelation.czerka_outpost.easy_czerka_outpost_guard")
require("mobile.revelation.czerka_outpost.easy_czerka_outpost_lieutenant")
require("mobile.revelation.czerka_outpost.easy_czerka_outpost_guard_r")
require("mobile.revelation.czerka_outpost.easy_czerka_outpost_lieutenant_r")

require("mobile.revelation.czerka_outpost.easy_czerka_outpost_crazy_droidengineer")
require("mobile.revelation.czerka_outpost.hard_czerka_outpost_crazy_droidengineer")
require("mobile.revelation.czerka_outpost.czerka_outpost_crazy_droidengineer")

require("mobile.revelation.czerka_outpost.eg6_bomb_droid")
require("mobile.revelation.czerka_outpost.deadly_czerka_outpost_mining_minecrawler_guardian")