require("loot.revelation.items.armor.snow_rebel.snowarmor_rebel_belt")
require("loot.revelation.items.armor.snow_rebel.snowarmor_rebel_bicep_l")
require("loot.revelation.items.armor.snow_rebel.snowarmor_rebel_bicep_r")
require("loot.revelation.items.armor.snow_rebel.snowarmor_rebel_boots")
require("loot.revelation.items.armor.snow_rebel.snowarmor_rebel_bracer_l")
require("loot.revelation.items.armor.snow_rebel.snowarmor_rebel_bracer_r")
require("loot.revelation.items.armor.snow_rebel.snowarmor_rebel_chest_plate")
require("loot.revelation.items.armor.snow_rebel.snowarmor_rebel_gloves")
require("loot.revelation.items.armor.snow_rebel.snowarmor_rebel_helmet")
require("loot.revelation.items.armor.snow_rebel.snowarmor_rebel_leggings")

