require("mobile.revelation.dungeons.rev_hd_firedroid")
require("mobile.revelation.dungeons.rev_hd_borvo_the_hutt")
require("mobile.revelation.dungeons.rev_hd_borvos_guard")
require("mobile.revelation.dungeons.rev_hd_fed_battle_droid")
require("mobile.revelation.dungeons.rev_hd_gamorrean_guard")
