--Copyright (C) 2015 <www.revelationonline.net> Author genesis@revelationonline.net


--which carries forward this exception.

-- GCW

object_revelation_tangible_wearables_armor_marine_shared_armor_marine_belt_gcw = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/marine/shared_armor_marine_belt_gcw.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_marine_shared_armor_marine_belt_gcw, "object/tangible/wearables/armor/marine/shared_armor_marine_belt_gcw.iff")

object_revelation_tangible_wearables_armor_marine_shared_armor_marine_bicep_l_gcw = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/marine/shared_armor_marine_bicep_l_gcw.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_marine_shared_armor_marine_bicep_l_gcw, "object/tangible/wearables/armor/marine/shared_armor_marine_bicep_l_gcw.iff")

object_revelation_tangible_wearables_armor_marine_shared_armor_marine_bicep_r_gcw = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/marine/shared_armor_marine_bicep_r_gcw.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_marine_shared_armor_marine_bicep_r_gcw, "object/tangible/wearables/armor/marine/shared_armor_marine_bicep_r_gcw.iff")

object_revelation_tangible_wearables_armor_marine_shared_armor_marine_bracer_l_gcw = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/marine/shared_armor_marine_bracer_l_gcw.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_marine_shared_armor_marine_bracer_l_gcw, "object/tangible/wearables/armor/marine/shared_armor_marine_bracer_l_gcw.iff")

object_revelation_tangible_wearables_armor_marine_shared_armor_marine_bracer_r_gcw = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/marine/shared_armor_marine_bracer_r_gcw.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_marine_shared_armor_marine_bracer_r_gcw, "object/tangible/wearables/armor/marine/shared_armor_marine_bracer_r_gcw.iff")

object_revelation_tangible_wearables_armor_marine_shared_armor_marine_chest_plate_rebel_gcw = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/marine/shared_armor_marine_chest_plate_rebel_gcw.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_marine_shared_armor_marine_chest_plate_rebel_gcw, "object/tangible/wearables/armor/marine/shared_armor_marine_chest_plate_rebel_gcw.iff")

object_revelation_tangible_wearables_armor_marine_shared_armor_marine_gloves_gcw = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/marine/shared_armor_marine_gloves_gcw.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_marine_shared_armor_marine_gloves_gcw, "object/tangible/wearables/armor/marine/shared_armor_marine_gloves_gcw.iff")

object_revelation_tangible_wearables_armor_marine_shared_armor_marine_helmet_gcw = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/marine/shared_armor_marine_helmet_gcw.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_marine_shared_armor_marine_helmet_gcw, "object/tangible/wearables/armor/marine/shared_armor_marine_helmet_gcw.iff")

object_revelation_tangible_wearables_armor_marine_shared_armor_marine_leggings_gcw = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/marine/shared_armor_marine_leggings_gcw.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_marine_shared_armor_marine_leggings_gcw, "object/tangible/wearables/armor/marine/shared_armor_marine_leggings_gcw.iff")

object_revelation_tangible_wearables_armor_marine_shared_armor_marine_boots_gcw = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/marine/shared_armor_marine_boots_gcw.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_marine_shared_armor_marine_boots_gcw, "object/tangible/wearables/armor/marine/shared_armor_marine_boots_gcw.iff")


