krayt_dragon_aged_ancient_fun = Creature:new {
	objectName = "",
	customName = "Krayt old ancient Dragonbeast",
	socialGroup = "krayt",
	faction = "",
	level = 380,
	chanceHit = 100.0,
	damageMin = 3570,
	damageMax = 5150,
	baseXp = 28549,
	baseHAM = 280000,
	baseHAMmax = 381000,
	armor = 1,
	resists = {35,35,35,35,35,35,35,35,35},
	meatType = "meat_carnivore",
	meatAmount = 7500,
	hideType = "hide_bristley",
	hideAmount = 7500,
	boneType = "bone_mammal",
	boneAmount = 7500,
	milk = 0,
	tamingChance = 0,
	ferocity = 30,
	pvpBitmask = AGGRESSIVE + ATTACKABLE + ENEMY,
	creatureBitmask = PACK + KILLER + STALKER,
	optionsBitmask = 128,
	diet = CARNIVORE,
	scale = 2.3,

	templates = {"object/mobile/krayt_dragon.iff"},
        lootGroups = {},
	weapons = {},
	conversationTemplate = "",
	attacks = {
		{"creatureareacombo","stateAccuracyBonus=125"},
		{"creatureareaknockdown","stateAccuracyBonus=180"},
		{"creatureareableeding","stateAccuracyBonus=180"},
		{"creatureareapoison","stateAccuracyBonus=180"},
	}
}

CreatureTemplates:addCreatureTemplate(krayt_dragon_aged_ancient_fun, "krayt_dragon_aged_ancient_fun")
