merchant_express_basic = Creature:new {
	objectName = "",
	customName = "Express Courier",
	faction = "",
	level = 100,
	chanceHit = 0.390000,
	damageMin = 290,
	damageMax = 300,
	baseXp = 2914,
	baseHAM = 8400,
	baseHAMmax = 10200,
	armor = 0,
	resists = {-1,-1,-1,-1,-1,-1,-1,-1,-1},
	meatType = "",
	meatAmount = 0,
	hideType = "",
	hideAmount = 0,
	boneType = "",
	boneAmount = 0,
	milk = 0,
	tamingChance = 0.000000,
	ferocity = 0,
	pvpBitmask = NONE,
	creatureBitmask = NONE,
	diet = HERBIVORE,
	templates = {
                "object/mobile/dressed_black_sun_guard.iff",
                "object/mobile/dressed_corsec_pilot_human_male_01.iff",
                "object/mobile/dressed_corsec_pilot_human_female_01.iff",
                "object/mobile/space_rebel_tier3_ezkiel.iff",
                "object/mobile/space_greeter_theed_freighter_captain.iff",
                "object/mobile/dressed_industrialist_trainer_01.iff",
                "object/mobile/space_privateer_tier1_corellia.iff"
    },
	conversationTemplate = "merchant_express_basic_template",
	optionsBitmask = 264
}
CreatureTemplates:addCreatureTemplate(merchant_express_basic,"merchant_express_basic")
