rev_at_at = Creature:new {
	objectName = "@mob/creature_names:at_at",
	socialGroup = "imperial",
	faction = "imperial",
	level = 300,
	chanceHit = 45,
	damageMin = 3270,
	damageMax = 4250,
	baseXp = 21728,
	baseHAM = 208000,
	baseHAMmax = 254000,
	armor = 3,
	resists = {90,90,10,90,90,90,90,100,15},
	meatType = "",
	meatAmount = 0,
	hideType = "",
	hideAmount = 0,
	boneType = "",
	boneAmount = 0,
	milk = 0,
	tamingChance = 0,
	ferocity = 0,
	pvpBitmask = ATTACKABLE + OVERT,
	creatureBitmask = PACK + KILLER,
	optionsBitmask = 128,
	diet = NONE,
	scale = 1.8,
	templates = {"object/mobile/atat.iff"},
	conversationTemplate = "",
	defaultAttack = "defaultdroidattack",
	defaultWeapon = "object/weapon/ranged/vehicle/vehicle_atst_ranged.iff",
}

CreatureTemplates:addCreatureTemplate(rev_at_at, "rev_at_at")
