--Copyright (C) 2015 <www.revelationonline.net> Author matthias.muente@gmx.de
-- Server Objects
require "object.revelation.mobile.vehicle.barc_speeder"
require "object.revelation.mobile.vehicle.pod_racer_one"
require "object.revelation.mobile.vehicle.pod_racer_two"
require "object.revelation.mobile.vehicle.barc_speeder_rebel"
require "object.revelation.mobile.vehicle.barc_speeder_imperial"
require "object.revelation.mobile.vehicle.swamp_speeder"
require "object.revelation.mobile.vehicle.basilisk_war_droid"
require "object.revelation.mobile.vehicle.hoverlifter_speeder"
require "object.revelation.mobile.vehicle.landspeeder_lava_skiff"
require "object.revelation.mobile.vehicle.landspeeder_v35"
require "object.revelation.mobile.vehicle.landspeeder_xp38"
--require "object.revelation.mobile.vehicle.landspeeder_ab1"
require "object.revelation.mobile.vehicle.sith_speeder"
require "object.revelation.mobile.vehicle.stap_speeder"
require "object.revelation.mobile.vehicle.tcg_military_transport"
require "object.revelation.mobile.vehicle.tcg_republic_gunship"