rev_morag_low = Creature:new {
	objectName = "",
	customName = "Morag Nightmare",
	socialGroup = "dungeon",
        level = 5,
        chanceHit = 95,
        damageMin = 20,
        damageMax = 50,
        baseXp = 500,
        baseHAM = 300,
        baseHAMmax = 400,
        armor = 0,
        resists = {55,55,60,55,55,70,55,55,20},
	meatType = "",
	meatAmount = 0,
	hideType = "",
	hideAmount = 0,
	boneType = "",
	boneAmount = 0,
	milk = 0,
	tamingChance = 0.000000,
	ferocity = 0,
        pvpBitmask = ATTACKABLE + ENEMY,
        creatureBitmask = PACK,
	optionsBitmask = 128,
	diet = HERBIVORE,
        scale = 3.5,
	templates = {"object/mobile/morag.iff"},
	lootGroups = {},
        weapons = {"czerka_melee_weapons_heavy"},
        attacks = merge(brawlermid,pikemanmid)
}

CreatureTemplates:addCreatureTemplate(rev_morag_low, "rev_morag_low")
