object_mobile_rev_city_dressed_dathomir_nightsister_spellweaver = object_mobile_shared_dressed_dathomir_nightsister_spellweaver:new {
	objectMenuComponent = {"cpp", "TrainerMenuComponent"}
}

ObjectTemplates:addTemplate(object_mobile_rev_city_dressed_dathomir_nightsister_spellweaver, "object/mobile/rev_city_dressed_dathomir_nightsister_spellweaver.iff")
