object_mobile_rev_city_dressed_criminal_swooper_zabrak_male_01 = object_mobile_shared_dressed_criminal_swooper_zabrak_male_01:new {
	objectMenuComponent = {"cpp", "TrainerMenuComponent"}
}

ObjectTemplates:addTemplate(object_mobile_rev_city_dressed_criminal_swooper_zabrak_male_01, "object/mobile/rev_city_dressed_criminal_swooper_zabrak_male_01.iff")
