object_mobile_rev_city_dressed_bounty_hunter_zabrak_female_01 = object_mobile_shared_dressed_bounty_hunter_zabrak_female_01:new {
	objectMenuComponent = {"cpp", "TrainerMenuComponent"}
}
ObjectTemplates:addTemplate(object_mobile_rev_city_dressed_bounty_hunter_zabrak_female_01, "object/mobile/rev_city_dressed_bounty_hunter_zabrak_female_01.iff")
