object_mobile_rev_city_dressed_rebel_pilot_sullustan_male_01 = object_mobile_shared_dressed_rebel_pilot_sullustan_male_01:new {
	objectMenuComponent = {"cpp", "TrainerMenuComponent"}
}

ObjectTemplates:addTemplate(object_mobile_rev_city_dressed_rebel_pilot_sullustan_male_01, "object/mobile/dressed_rev_city_rebel_pilot_sullustan_male_01.iff")
