require "object.revelation.draft_schematic.armor.objects"
require "object.revelation.draft_schematic.clothing.objects"
require "object.revelation.draft_schematic.furniture.objects"
require "object.revelation.draft_schematic.structure.objects"
--require "object.revelation.draft_schematic.vehicle.objects"
