require ("mobile.revelation_conversations.dathomir_village_transit_conversation")
require ("mobile.revelation_conversations.gcw.serverobjects")
require ("mobile.revelation_conversations.interaction_npc.serverobjects")
require ("mobile.revelation_conversations.merchants.serverobjects")
require ("mobile.revelation_conversations.quest.serverobjects")
require ("mobile.revelation_conversations.czerka_outpost.serverobjects")
require ("mobile.revelation_conversations.trainer.serverobjects")
require ("mobile.revelation_conversations.transit.serverobjects")