--Copyright (C) 2015 <www.revelationonline.net> Author genesis@revelationonline.net


--which carries forward this exception.

--Belt

object_revelation_tangible_wearables_armor_mandalorian_rebel_shared_armor_mandalorian_rebel_belt = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/mandalorian_rebel/shared_armor_mandalorian_rebel_belt.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_mandalorian_rebel_shared_armor_mandalorian_rebel_belt, "object/tangible/wearables/armor/mandalorian_rebel/shared_armor_mandalorian_rebel_belt.iff")

--Bicep Left

object_revelation_tangible_wearables_armor_mandalorian_rebel_shared_armor_mandalorian_rebel_bicep_l = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/mandalorian_rebel/shared_armor_mandalorian_rebel_bicep_l.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_mandalorian_rebel_shared_armor_mandalorian_rebel_bicep_l, "object/tangible/wearables/armor/mandalorian_rebel/shared_armor_mandalorian_rebel_bicep_l.iff")

--Bicep Right

object_revelation_tangible_wearables_armor_mandalorian_rebel_shared_armor_mandalorian_rebel_bicep_r = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/mandalorian_rebel/shared_armor_mandalorian_rebel_bicep_r.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_mandalorian_rebel_shared_armor_mandalorian_rebel_bicep_r, "object/tangible/wearables/armor/mandalorian_rebel/shared_armor_mandalorian_rebel_bicep_r.iff")

--Bracer Right

object_revelation_tangible_wearables_armor_mandalorian_rebel_shared_armor_mandalorian_rebel_bracer_l = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/mandalorian_rebel/shared_armor_mandalorian_rebel_bracer_l.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_mandalorian_rebel_shared_armor_mandalorian_rebel_bracer_l, "object/tangible/wearables/armor/mandalorian_rebel/shared_armor_mandalorian_rebel_bracer_l.iff")

--Bracer Left

object_revelation_tangible_wearables_armor_mandalorian_rebel_shared_armor_mandalorian_rebel_bracer_r = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/mandalorian_rebel/shared_armor_mandalorian_rebel_bracer_r.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_mandalorian_rebel_shared_armor_mandalorian_rebel_bracer_r, "object/tangible/wearables/armor/mandalorian_rebel/shared_armor_mandalorian_rebel_bracer_r.iff")

--Chest Plate

object_revelation_tangible_wearables_armor_mandalorian_rebel_shared_armor_mandalorian_rebel_chest_plate = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/mandalorian_rebel/shared_armor_mandalorian_rebel_chest_plate.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_mandalorian_rebel_shared_armor_mandalorian_rebel_chest_plate, "object/tangible/wearables/armor/mandalorian_rebel/shared_armor_mandalorian_rebel_chest_plate.iff")

--Gloves

object_revelation_tangible_wearables_armor_mandalorian_rebel_shared_armor_mandalorian_rebel_gloves = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/mandalorian_rebel/shared_armor_mandalorian_rebel_gloves.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_mandalorian_rebel_shared_armor_mandalorian_rebel_gloves, "object/tangible/wearables/armor/mandalorian_rebel/shared_armor_mandalorian_rebel_gloves.iff")

--Helmet

object_revelation_tangible_wearables_armor_mandalorian_rebel_shared_armor_mandalorian_rebel_helmet = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/mandalorian_rebel/shared_armor_mandalorian_rebel_helmet.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_mandalorian_rebel_shared_armor_mandalorian_rebel_helmet, "object/tangible/wearables/armor/mandalorian_rebel/shared_armor_mandalorian_rebel_helmet.iff")

--Leggings

object_revelation_tangible_wearables_armor_mandalorian_rebel_shared_armor_mandalorian_rebel_leggings = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/mandalorian_rebel/shared_armor_mandalorian_rebel_leggings.iff"

}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_mandalorian_rebel_shared_armor_mandalorian_rebel_leggings, "object/tangible/wearables/armor/mandalorian_rebel/shared_armor_mandalorian_rebel_leggings.iff")

--Boots

object_revelation_tangible_wearables_armor_mandalorian_rebel_shared_armor_mandalorian_rebel_boots = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/wearables/armor/mandalorian_rebel/shared_armor_mandalorian_rebel_boots.iff"
	
}

ObjectTemplates:addClientTemplate(object_revelation_tangible_wearables_armor_mandalorian_rebel_shared_armor_mandalorian_rebel_boots, "object/tangible/wearables/armor/mandalorian_rebel/shared_armor_mandalorian_rebel_boots.iff")
