object_revelation_mobile_skeleton_undead_humanoid = object_revelation_mobile_skeleton_shared_undead_humanoid:new {

}

ObjectTemplates:addTemplate(object_revelation_mobile_skeleton_undead_humanoid, "object/mobile/skeleton/undead_humanoid.iff")
