object_revelation_tangible_painting_painting_loot_heroic_exar_kun = object_revelation_tangible_painting_painting_loot_heroic_exar_kun_shared:new {
customName = "Heroic Exar Kun"
}

ObjectTemplates:addTemplate(object_revelation_tangible_painting_painting_loot_heroic_exar_kun, "object/tangible/painting/painting_loot_heroic_exar_kun.iff")
