object_revelation_tangible_painting_painting_heroic_exar_kun_ultra_rare = object_revelation_tangible_painting_painting_heroic_exar_kun_ultra_rare_shared:new {
customName = "Heroic Exar Kun II"
}

ObjectTemplates:addTemplate(object_revelation_tangible_painting_painting_heroic_exar_kun_ultra_rare, "object/tangible/painting/painting_heroic_exar_kun_ultra_rare.iff")
