--Copyright (C) 2009 <SWGEmu>


--which carries forward this exception.

--VIP Bunker Schem
object_revelation_draft_schematic_structure_shared_vipbunker_house_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_vipbunker_house_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_vipbunker_house_schem, "object/draft_schematic/structure/shared_vipbunker_house_schem.iff")

--atat Schem
object_revelation_draft_schematic_structure_shared_atat_house_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_atat_house_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_atat_house_schem, "object/draft_schematic/structure/shared_atat_house_schem.iff")

--bespin Schem
object_revelation_draft_schematic_structure_shared_bespin_house_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_bespin_house_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_bespin_house_schem, "object/draft_schematic/structure/shared_bespin_house_schem.iff")

--commando Schem
object_revelation_draft_schematic_structure_shared_commando_house_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_commando_house_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_commando_house_schem, "object/draft_schematic/structure/shared_commando_house_schem.iff")

--emperors Schem
object_revelation_draft_schematic_structure_shared_emperors_house_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_emperors_house_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_emperors_house_schem, "object/draft_schematic/structure/shared_emperors_house_schem.iff")

--hangar Schem
object_revelation_draft_schematic_structure_shared_hangar_house_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_hangar_house_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_hangar_house_schem, "object/draft_schematic/structure/shared_hangar_house_schem.iff")

--jabbas Schem
object_revelation_draft_schematic_structure_shared_jabbas_house_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_jabbas_house_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_jabbas_house_schem, "object/draft_schematic/structure/shared_jabbas_house_schem.iff")

--jedi Schem
object_revelation_draft_schematic_structure_shared_jedi_house_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_jedi_house_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_jedi_house_schem, "object/draft_schematic/structure/shared_jedi_house_schem.iff")

--musty Schem
object_revelation_draft_schematic_structure_shared_musty_house_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_musty_house_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_musty_house_schem, "object/draft_schematic/structure/shared_musty_house_schem.iff")

--rebel Schem
object_revelation_draft_schematic_structure_shared_rebel_house_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_rebel_house_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_rebel_house_schem, "object/draft_schematic/structure/shared_rebel_house_schem.iff")

--relaxation Schem
object_revelation_draft_schematic_structure_shared_relaxation_house_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_relaxation_house_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_relaxation_house_schem, "object/draft_schematic/structure/shared_relaxation_house_schem.iff")

--sandcrawler Schem
object_revelation_draft_schematic_structure_shared_sandcrawler_house_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_sandcrawler_house_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_sandcrawler_house_schem, "object/draft_schematic/structure/shared_sandcrawler_house_schem.iff")

--sith Schem
object_revelation_draft_schematic_structure_shared_sith_house_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_sith_house_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_sith_house_schem, "object/draft_schematic/structure/shared_sith_house_schem.iff")

--tree Schem
object_revelation_draft_schematic_structure_shared_tree_house_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_tree_house_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_tree_house_schem, "object/draft_schematic/structure/shared_tree_house_schem.iff")

--vehicle Schem
object_revelation_draft_schematic_structure_shared_vehicle_house_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_vehicle_house_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_vehicle_house_schem, "object/draft_schematic/structure/shared_vehicle_house_schem.iff")

--yoda Schem
object_revelation_draft_schematic_structure_shared_yoda_house_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_yoda_house_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_yoda_house_schem, "object/draft_schematic/structure/shared_yoda_house_schem.iff")

--yt1300 Schem
object_revelation_draft_schematic_structure_shared_yt1300_house_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_yt1300_house_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_yt1300_house_schem, "object/draft_schematic/structure/shared_yt1300_house_schem.iff")

--gen_lg_win_01_schem Schem
object_revelation_draft_schematic_structure_shared_gen_lg_win_01_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_gen_lg_win_01_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_gen_lg_win_01_schem, "object/draft_schematic/structure/shared_gen_lg_win_01_schem.iff")

--gen_lg_win_02_schem Schem
object_revelation_draft_schematic_structure_shared_gen_lg_win_02_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_gen_lg_win_02_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_gen_lg_win_02_schem, "object/draft_schematic/structure/shared_gen_lg_win_02_schem.iff")

--gen_md_win_01_schem Schem
object_revelation_draft_schematic_structure_shared_gen_md_win_01_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_gen_md_win_01_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_gen_md_win_01_schem, "object/draft_schematic/structure/shared_gen_md_win_01_schem.iff")

--gen_md_win_02_schem Schem
object_revelation_draft_schematic_structure_shared_gen_md_win_02_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_gen_md_win_02_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_gen_md_win_02_schem, "object/draft_schematic/structure/shared_gen_md_win_02_schem.iff")

--gen_sm_win_01_schem Schem
object_revelation_draft_schematic_structure_shared_gen_sm_win_01_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_gen_sm_win_01_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_gen_sm_win_01_schem, "object/draft_schematic/structure/shared_gen_sm_win_01_schem.iff")

--gen_sm_win_02_schem Schem
object_revelation_draft_schematic_structure_shared_gen_sm_win_02_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_gen_sm_win_02_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_gen_sm_win_02_schem, "object/draft_schematic/structure/shared_gen_sm_win_02_schem.iff")

--nab_sm_win_01_schem Schem
object_revelation_draft_schematic_structure_shared_nab_sm_win_01_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_nab_sm_win_01_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_nab_sm_win_01_schem, "object/draft_schematic/structure/shared_nab_sm_win_01_schem.iff")

--tat_sm_win_01_schem Schem
object_revelation_draft_schematic_structure_shared_tat_sm_win_01_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_tat_sm_win_01_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_tat_sm_win_01_schem, "object/draft_schematic/structure/shared_tat_sm_win_01_schem.iff")

--rebel bunker schem
object_revelation_draft_schematic_structure_shared_rebel_bunker_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_rebel_bunker_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_rebel_bunker_schem, "object/draft_schematic/structure/shared_rebel_bunker_schem.iff")

--Diner Schem
object_revelation_draft_schematic_structure_shared_diner_schem = SharedDraftSchematicObjectTemplate:new {
	clientTemplateFileName = "object/draft_schematic/structure/shared_diner_schem.iff"
}
ObjectTemplates:addClientTemplate(object_revelation_draft_schematic_structure_shared_diner_schem, "object/draft_schematic/structure/shared_diner_schem.iff")

