require("loot.revelation.items.armor.bh_armor_rare_belt")
require("loot.revelation.items.armor.bh_armor_rare_bicep_l")
require("loot.revelation.items.armor.bh_armor_rare_bicep_r")
require("loot.revelation.items.armor.bh_armor_rare_boots")
require("loot.revelation.items.armor.bh_armor_rare_bracer_l")
require("loot.revelation.items.armor.bh_armor_rare_bracer_r")
require("loot.revelation.items.armor.bh_armor_rare_chest_plate")
require("loot.revelation.items.armor.bh_armor_rare_gloves")
require("loot.revelation.items.armor.bh_armor_rare_helmet")
require("loot.revelation.items.armor.bh_armor_rare_leggings")

require("loot.revelation.items.armor.marauder.serverobjects")
require("loot.revelation.items.armor.snow_rebel.serverobjects")
require("loot.revelation.items.armor.snow_imperial.serverobjects")
