object_revelation_intangible_beast_bm_mutated_rancor = object_revelation_intangible_beast_shared_bm_mutated_rancor:new {

}

ObjectTemplates:addTemplate(object_revelation_intangible_beast_bm_mutated_rancor, "object/intangible/beast/bm_mutated_rancor.iff")
